final String url = 'https://stark-wave-13126.herokuapp.com/';
final String loginUrl = url + 'api/v1/auth/signin/';
final String productDetails = url + 'api/v1/products/';
final String signupURL = url + 'api/v1/auth/signup/';
final String addProduct = url + 'api/v1/products/';
final String updateProd = url + 'api/v1/products/';
final String removeProd = url + 'api/v1/products/';
final String dispactProd = url + 'api/v1/products/dispatch/';
final String statsurl = url + 'api/v1/stats/';
